# permissions for end users to view resources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: resource-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: k8s-resource-operator
    app.kubernetes.io/part-of: k8s-resource-operator
    app.kubernetes.io/managed-by: kustomize
  name: resource-viewer-role
rules:
- apiGroups:
  - resource.example.com
  resources:
  - resources
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - resource.example.com
  resources:
  - resources/status
  verbs:
  - get
